version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ejemplo_db
      MYSQL_USER: exequielsuica99
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - '3307:3306'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db